### ISSUE TITLE
Unable to Build bootloader

### ISSUE THREAD

**Issue by itskarthig** [lorabasics/basicmac#18]
HI 

Unable to build bootloader

`arm-none-eabi-gcc -std=gnu11 -DSTM32L0 -DSTM32L073xx -DUP_PAGEBUFFER_SZ=64 -DBOOT_LED_GPIO="GPIO('A',5,0)" -MMD -MP -g -mcpu=cortex-m0plus -I../../../src/common -fno-common -fno-builtin -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -I../../../src/arm/CMSIS/Include -Wall -Os -I../../../src/arm/CMSIS/Device/ST/STM32L0xx/Include   -c -o bootloader.o ../../../src/arm/stm32lx/bootloader.c
../../../src/arm/stm32lx/bootloader.c:1:0: error: target CPU does not support ARM mode
 // Copyright (C) 2016-2019 Semtech (International) AG. All rights reserved.
 ^
<builtin>: recipe for target 'bootloader.o' failed
make: *** [bootloader.o] Error 1`

**Comment by mkuyper** [comment]
What version of arm-non-eabi-gcc are you using? Some older versions do not automatically infer Thumb mode from the `-mcpu=cortex-m0plus` option. We recommend using at least version 7.3.1.

Alternatively, you can try adding `FLAGS	+= -mthumb` to the file basicloader/build/makefiles/stm32lx.mk below the line that says `FLAGS           += -mcpu=cortex-m0plus`.

**Comment by itskarthig** [comment]
Thanks @mkuyper
