### ISSUE TITLE
Application Startup (appstart) service call is required or mandatory ?

### ISSUE THREAD

**Issue by Rush4iot** [lorabasics/basicmac#4]
In programming model [page](https://doc.sm.tc/mac/programming.html) it is written: `It is recommended that applications make use of the Application Startup (appstart) service to provide the correct initialization for the run-time environment.`.

Is it recommended or mandatory ?

Olivier

**Comment by mkuyper** [comment]
It is highly recommended that applications make use of the *appstart* and the *lwmux* services. The [ex-join](https://github.com/lorabasics/basicmac/tree/master/projects/ex-join) example illustrates how to make use of those.
