### ISSUE TITLE
os_runloop() clarification

### ISSUE THREAD

**Issue by Rush4iot** [lorabasics/basicmac#6]
https://doc.sm.tc/mac/programming.html#c.os_runloop

It might be great to add something like "It should be called only one time" so users now they do not have to call in again in the callbacks, and maybe rename it to os_runInifiniteLoop() ?

**Comment by mkuyper** [comment]
Correct. The documentation says (emphasis added):

> Executes run-time jobs from the timer and from the run queues. This function is the main action dispatcher. It must be run on the main thread **and doesn’t return**.

We can clarify this to make it more clear.

It is recommended that applications make use of the higher-level *[appstart](https://doc.sm.tc/mac/appstart.html)* service that inititalizes the run-time correctly and takes care of running the scheduler; i.e. calling `os_runlop()` function at the appropriate time and exactly once.
