### ISSUE TITLE
Low-power modes

### ISSUE THREAD

**Issue by SloMusti** [lorabasics/basicmac#9]
Low-power modes, are they implemented or in what way? If there is an example for configuring low-power modes in the application, please provide it.

**Comment by tkramp** [comment]
Please take questions like this to the forum in the just opened [Developer Portal](https://lora-developers.semtech.com/knowledge-base/forum/viewforum/33/). Thanks!

**Comment by mkuyper** [comment]
The handling of sleep falls into the domain of the HAL. Please see [this thread](https://lora-developers.semtech.com/knowledge-base/forum/viewthread/18/) on the Developer Portal for an explanation on how it is implemented for the STM32 reference HAL.
